services:
  - type: web
    name: civicpulse
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_TOMTOM_API_KEY
        value: iQS1YElqYlJ08jdGeMARItWgrsyltfHs
